# syntax=docker/dockerfile:1.7

ARG KEYCLOAK_IMAGE=quay.io/keycloak/keycloak:26.7.4@sha256:82a77884f3af238beab1e7afd63b5f530e1b5c0590bd7aa60b40a40463e29b2c

FROM ${KEYCLOAK_IMAGE} AS builder
ENV KC_DB=postgres
ENV KC_HEALTH_ENABLED=true
ENV KC_HTTP_MANAGEMENT_HEALTH_ENABLED=true
RUN /opt/keycloak/bin/kc.sh build

FROM ${KEYCLOAK_IMAGE}
COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY --chmod=0444 infra/keycloak/quantum-platform-realm.json /opt/keycloak/data/import/quantum-platform-realm.json
COPY --chmod=0555 infra/keycloak/platform-entrypoint.sh /opt/keycloak/bin/qcrm-platform-entrypoint
COPY --chmod=0555 infra/keycloak/bootstrap-provisioner.sh /opt/keycloak/bin/qcrm-bootstrap-provisioner
USER 0
RUN chmod 0555 /opt/keycloak/data /opt/keycloak/data/import
USER 1000
ENTRYPOINT ["/opt/keycloak/bin/qcrm-platform-entrypoint"]
CMD ["start", "--optimized", "--import-realm"]
